### ISSUE TITLE
About bandwidth selection of large samples

### ISSUE THREAD

**Issue by xuzzhan** [pysal/mgwr#127] opened 2023-09-17 04:07 UTC
My sample size is relatively large, reaching more than 20k. So I have several questions about how to improve run speed.

1. About iteration times
If I use golden search to achieve the best iteration times, it will take a huge time cost. So is there any place where I can set the threshold of the number of iterations? Like when it reaches 20 times, the iteration stops and returns the best bandwidths.

2. About preset bandwidth
Or another method is to preset the bandwidth for each variable. I wonder if MGWR software or python supports users to set the bandwidth of each variable in advance?

The screenshot shows that I have iterated over 100 times. I really want to stop it at this time and choose the best bandwidths to fit the data.
![MGWR](https://github.com/pysal/mgwr/assets/130918955/1086fac7-a3f7-44e3-be84-5652f71e89c0)

**Comment by TongCWei** [comment] 2023-10-24 07:06
似乎可以使用python的mgwr库，似乎设置了最多迭代200次

**Comment by xuzzhan** [comment] 2023-10-24 07:12
> 似乎可以使用python的mgwr库，似乎设置了最多迭代200次

感谢提醒！我之前发现了python的mgwr库的内部函数，但是没有研究明白。我进入函数内部修改了一些参数，比如迭代次数、预设带宽等，但是一直没有跑出来结果直到python崩溃。所以我后来采用的方法是修改mgwr软件中的收敛准则，比如将阈值从0.00001改为0.001，后面速度就很快了。

但是新的问题在于，跑出来的mgwr的结果明显比gwr的要差，Adj R²更低，AIC要高不少。这是一个新问题。因为原则上应该会根据GWR的结果再去优化各变量带宽才对，理论上结果应该要比GWR更好。

**Comment by martinfleis** [comment] 2023-11-02 17:05
The `BW_Sel` function could also be optimised on our side. We run whole GWR many times while re-doing everything in every iteration (like distance matrices) while those could technically be re-used.

**Comment by TaylorOshan** [comment] 2023-11-03 22:00
As pointed out by @TongCWei , he couldn't symbol to play with the two different convergence criteria, such a tolerance for magnitude, or the number of iterations, but that's not typically ideal. More often than not, a lack of convergence is signaling a more significant problem. As @Ziqi-Li pointed out, you have a thing like 38 variables in your model, which is a huge amount for gwr/mgwr, and still large for any type of interpreter ball regression model. You could try to be more selective about the variables that you are putting into your model, making sure that they all have a sound theoretical basis and reducing number that are complimentary/collinear to each other in order to put a more parsimonious model before searching for bandwidths. In addition, you could also set some of the bandwidths manually so you don't have to search for as many in order to reduce the computational load. This can be done by setting the minimum and maximum bandwidth to the same target value. Something like this when you are trying to set the minimum or maximum bandwidth across an entire set of variables (i.e., GWR):

`bw = selector.search(multi_bw_min=[75], multi_bw_max=[75])`


And something like this, if you are trying to set individual restrictions with some varying and others not for a set of 5 covariates and 500 observations:

`bw = selector.search(multi_bw_min=[150, 45, 45, 400, 45], multi_bw_max=[150, 45, 45, 400, 45])`

Just be aware that you don't want to set too small of a minimum value because that could equally cause you to run into some issues (i.e., very small sample size for each local regression) in the case of the nearest neighbor bandwidth.

**Comment by TaylorOshan** [comment] 2023-11-03 22:08
@martinfleis it could be possible to optimize, but if I recall correctly we are not actually re-computing and storing entire distance matrix/weights and instead compute each row needed for each local regression as it is needed. This was to avoid memory bottlenecks associated with storing really large and dense `W` matrix, since in GWR we don't typically truncate enforce to zero beyond a threshold to ensure sparser `W`. I may be remembering incorrectly though, and if we do this for the weights, but not for the distances, then that could indeed be a place for improvement. @Ziqi-Li would likely have useful input.

**Comment by martinfleis** [comment] 2023-11-03 22:18
@TaylorOshan Ah, a good old balance between memory and computation... I guess you are right.

**Comment by Ziqi-Li** [comment] 2023-11-06 22:49
@martinfleis @TaylorOshanYes, Taylor is correct; the memory is a bigger bottleneck here. We deliberately don't store W. There is also a consideration about parallelization; if we were to store W, we would have to store it in each process to avoid excessive memory I/O, which would add even more to the memory footprint. There might be a smarter way to do this now, given that the parallelization implementation has been there for a few years.

@xuzzhan I will close this thread. If there is anything else you think should be discussed further, feel free to reopen it.

**Closed by Ziqi-Li** 2023-11-06 22:49 UTC
